### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by kouhei-github** [prat96/FLIR_to_Yolo#1]
File "FLIR_2_yolo.py", line 19, in <module>
    images = data['images']
KeyError: 'images'

There is no image key in the joson file.
Is it an image?

**Comment by prat96** [comment]
Hello! 

Actually FLIR keeps changing the Json format, when I downloaded the dataset, there was 'images' key in the json file.

Example:
```
{
  "images": [
    {
      "file_name": "thermal_8_bit/FLIR_video_00001.jpeg",
      "id": 0,
      "subdirs": ".",
      "height": 512,
      "width": 640,
      "extra_info": {}
    },
    {
      "file_name": "thermal_8_bit/FLIR_video_00002.jpeg",
      "id": 1,
       and so on....
```

So you can modify the script after checking which keys are there in your version of json file.
