### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './output/FLIR_00001.txt

### ISSUE THREAD

**Issue by joel5638** [prat96/FLIR_to_Yolo#2]
trying to run the FLIR_2_YOLO.py and i get this error. the paths are correct. I see that FLIR annotation.json is not in COCO format. Can you see if you can help?

thanks

**Comment by prat96** [comment]
Could you please post the full terminal output? And please attach your JSON file.

**Comment by A-levy** [comment]
I'v met the same error.Then I changed
file = open('./output_path/ + str(image_name) + '.txt', 'w+') 
to
file = open(args.output_path + str(image_name) + '.txt', 'w+')
It works
